# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JarvisUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_background(object):
    def setupUi(self, background):
        background.setObjectName("background")
        background.resize(1163, 772)
        background.setStyleSheet("background-color: black;")
        self.ironmanbackground = QtWidgets.QLabel(background)
        self.ironmanbackground.setGeometry(QtCore.QRect(880, 0, 281, 351))
        self.ironmanbackground.setStyleSheet("background-color: transparent;")
        self.ironmanbackground.setText("")
        self.ironmanbackground.setPixmap(QtGui.QPixmap("C:\\Users\\91914\\Project\\GUI files\\Iron_Template.jpg"))
        self.ironmanbackground.setScaledContents(True)
        self.ironmanbackground.setObjectName("ironmanbackground")
        self.start = QtWidgets.QLabel(background)
        self.start.setGeometry(QtCore.QRect(690, 650, 231, 111))
        self.start.setText("")
        self.start.setPixmap(QtGui.QPixmap("C:\\Users\\91914\\Project\\GUI files\\Start.png"))
        self.start.setScaledContents(True)
        self.start.setObjectName("start")
        self.jarvisgui = QtWidgets.QLabel(background)
        self.jarvisgui.setGeometry(QtCore.QRect(70, 70, 711, 351))
        self.jarvisgui.setText("")
        self.jarvisgui.setPixmap(QtGui.QPixmap("C:\\Users\\91914\\Project\\GUI files\\Jarvis_Gui (1).gif"))
        self.jarvisgui.setObjectName("jarvisgui")
        self.quit = QtWidgets.QLabel(background)
        self.quit.setGeometry(QtCore.QRect(920, 660, 221, 91))
        self.quit.setText("")
        self.quit.setPixmap(QtGui.QPixmap("C:\\Users\\91914\\Project\\GUI files\\Quit.png"))
        self.quit.setScaledContents(True)
        self.quit.setObjectName("quit")
        self.label_4 = QtWidgets.QLabel(background)
        self.label_4.setGeometry(QtCore.QRect(30, 550, 251, 101))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:\\Users\\91914\\Project\\GUI files\\gggf.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(background)
        self.label_6.setGeometry(QtCore.QRect(30, 660, 251, 101))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("C:\\Users\\91914\\Project\\GUI files\\gggf.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.ironman = QtWidgets.QLabel(background)
        self.ironman.setGeometry(QtCore.QRect(690, 380, 451, 291))
        self.ironman.setText("")
        self.ironman.setPixmap(QtGui.QPixmap("C:\\Users\\91914\\Project\\GUI files\\Iron_Template_1.gif"))
        self.ironman.setScaledContents(True)
        self.ironman.setObjectName("ironman")
        self.earth = QtWidgets.QLabel(background)
        self.earth.setGeometry(QtCore.QRect(330, 510, 301, 241))
        self.earth.setText("")
        self.earth.setPixmap(QtGui.QPixmap("C:\\Users\\91914\\Project\\GUI files\\Earth.gif"))
        self.earth.setScaledContents(True)
        self.earth.setObjectName("earth")
        self.datetextbrowser = QtWidgets.QTextBrowser(background)
        self.datetextbrowser.setGeometry(QtCore.QRect(43, 570, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.datetextbrowser.setFont(font)
        self.datetextbrowser.setStyleSheet("background-color: transparent;\n"
"border:none;\n"
"color:white;\n"
"border-radius:none;")
        self.datetextbrowser.setObjectName("datetextbrowser")
        self.timelabel = QtWidgets.QTextBrowser(background)
        self.timelabel.setGeometry(QtCore.QRect(45, 680, 250, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.timelabel.setFont(font)
        self.timelabel.setStyleSheet("background-color: transparent;\n"
"border:none;\n"
"color:white;\n"
"border-radius:none;")
        self.timelabel.setObjectName("timelabel")
        self.startpushButton = QtWidgets.QPushButton(background)
        self.startpushButton.setGeometry(QtCore.QRect(700, 670, 211, 71))
        self.startpushButton.setStyleSheet("background-color:transparent;")
        self.startpushButton.setText("")
        self.startpushButton.setObjectName("startpushButton")
        self.quitpushButton = QtWidgets.QPushButton(background)
        self.quitpushButton.setGeometry(QtCore.QRect(930, 670, 201, 71))
        self.quitpushButton.setStyleSheet("background-color:transparent;")
        self.quitpushButton.setText("")
        self.quitpushButton.setObjectName("quitpushButton")
        self.ironmanbackground.raise_()
        self.start.raise_()
        self.jarvisgui.raise_()
        self.quit.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.ironman.raise_()
        self.earth.raise_()
        self.startpushButton.raise_()
        self.quitpushButton.raise_()
        self.datetextbrowser.raise_()
        self.timelabel.raise_()

        self.retranslateUi(background)
        QtCore.QMetaObject.connectSlotsByName(background)

    def retranslateUi(self, background):
        _translate = QtCore.QCoreApplication.translate
        background.setWindowTitle(_translate("background", "A.I Desktop Voice Assitsant with Home Automation"))
        self.datetextbrowser.setHtml(_translate("background", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nirmala UI\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Date: 07-04-23</span></p></body></html>"))
        self.timelabel.setHtml(_translate("background", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nirmala UI\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Time: 07:31:15</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    background = QtWidgets.QWidget()
    ui = Ui_background()
    ui.setupUi(background)
    background.show()
    sys.exit(app.exec_())
