# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JARVISmainfile.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1400, 850)
        Frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.head = QtWidgets.QLabel(Frame)
        self.head.setGeometry(QtCore.QRect(20, 10, 1351, 161))
        self.head.setText("")
        self.head.setPixmap(QtGui.QPixmap("C:\\Users\\91914\\Project\\GUI files\\heading.jpg"))
        self.head.setScaledContents(True)
        self.head.setObjectName("head")
        self.ironman = QtWidgets.QLabel(Frame)
        self.ironman.setGeometry(QtCore.QRect(1140, 170, 331, 581))
        self.ironman.setStyleSheet("border-image: url(C:/Users/91914/Project/GUI files/ironman-portrait.webp);")
        self.ironman.setObjectName("ironman")
        self.arcreact = QtWidgets.QLabel(Frame)
        self.arcreact.setGeometry(QtCore.QRect(670, 170, 431, 371))
        self.arcreact.setStyleSheet("border-image: url(C:/Users/91914/Project/GUI files/techcircle.gif);")
        self.arcreact.setText("")
        self.arcreact.setScaledContents(True)
        self.arcreact.setObjectName("arcreact")
        self.load = QtWidgets.QLabel(Frame)
        self.load.setGeometry(QtCore.QRect(360, 250, 251, 221))
        self.load.setStyleSheet("border-image: url(C:/Users/91914/Project/GUI files/tech loading-cropped.gif);")
        self.load.setScaledContents(True)
        self.load.setObjectName("load")
        self.listen = QtWidgets.QLabel(Frame)
        self.listen.setGeometry(QtCore.QRect(360, 240, 251, 241))
        self.listen.setStyleSheet("border-image: url(C:/Users/91914/Project/GUI files/listening.gif);")
        self.listen.setScaledContents(True)
        self.listen.setObjectName("listen")
        self.codelabel = QtWidgets.QLabel(Frame)
        self.codelabel.setGeometry(QtCore.QRect(10, 190, 301, 211))
        self.codelabel.setStyleSheet("border-image: url(C:/Users/91914/Project/GUI files/B.G_Template_1.gif);")
        self.codelabel.setText("")
        self.codelabel.setScaledContents(True)
        self.codelabel.setObjectName("codelabel")
        self.speak = QtWidgets.QLabel(Frame)
        self.speak.setGeometry(QtCore.QRect(360, 230, 271, 261))
        self.speak.setStyleSheet("border-image: url(C:/Users/91914/Project/GUI files/speaking.gif);")
        self.speak.setScaledContents(True)
        self.speak.setObjectName("speak")
        self.earth = QtWidgets.QLabel(Frame)
        self.earth.setGeometry(QtCore.QRect(1040, 600, 191, 131))
        self.earth.setStyleSheet("\n"
"border-image: url(C:/Users/91914/Project/GUI files/Earth_Template.gif);")
        self.earth.setScaledContents(True)
        self.earth.setObjectName("earth")
        self.textBrowser = QtWidgets.QTextBrowser(Frame)
        self.textBrowser.setGeometry(QtCore.QRect(10, 460, 301, 71))
        self.textBrowser.setStyleSheet("border:2px solid white;\n"
"font: 75 24pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(255, 255, 255);\n")
        self.textBrowser.setObjectName("textBrowser")
        self.start = QtWidgets.QPushButton(Frame)
        self.start.setGeometry(QtCore.QRect(1060, 770, 161, 71))
        self.start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 75 20pt \"Leelawadee\";\n"
"color: rgb(255, 255, 255);\n"
"border : 1px solid white;")
        self.start.setObjectName("start")
        self.quit = QtWidgets.QPushButton(Frame)
        self.quit.setGeometry(QtCore.QRect(1230, 770, 151, 71))
        self.quit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.quit.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 75 20pt \"Leelawadee\";\n"
"color: rgb(255, 255, 255);\n"
"border : 1px solid white;")
        self.quit.setObjectName("quit")
        self.terminalOutputBox = QtWidgets.QPlainTextEdit(Frame)
        self.terminalOutputBox.setGeometry(QtCore.QRect(10, 570, 1031, 271))
        font = QtGui.QFont()
        font.setFamily("\"Karisma\"")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.terminalOutputBox.setFont(font)
        self.terminalOutputBox.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.terminalOutputBox.setMouseTracking(True)
        self.terminalOutputBox.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background: transparent;\n"
"font:14pt \\\"Karisma\\\";\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px 1px 1px 1px;\n"
"padding-left:5px;")
        self.terminalOutputBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.terminalOutputBox.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.terminalOutputBox.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.terminalOutputBox.setReadOnly(True)
        self.terminalOutputBox.setOverwriteMode(True)
        self.terminalOutputBox.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.terminalOutputBox.setCenterOnScroll(True)
        self.terminalOutputBox.setObjectName("terminalOutputBox")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.ironman.setText(_translate("Frame", "TextLabel"))
        self.load.setText(_translate("Frame", "TextLabel"))
        self.listen.setText(_translate("Frame", "TextLabel"))
        self.speak.setText(_translate("Frame", "TextLabel"))
        self.earth.setText(_translate("Frame", "TextLabel"))
        self.start.setText(_translate("Frame", "START"))
        self.quit.setText(_translate("Frame", "QUIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
