# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1000, 830)
        Frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.heading = QtWidgets.QLabel(Frame)
        self.heading.setGeometry(QtCore.QRect(0, 0, 1011, 161))
        self.heading.setText("")
        self.heading.setPixmap(QtGui.QPixmap("C:\\Users\\91914\\Project\\GUI files\\heading.jpg"))
        self.heading.setScaledContents(True)
        self.heading.setObjectName("heading")
        self.maingif = QtWidgets.QLabel(Frame)
        self.maingif.setGeometry(QtCore.QRect(0, 170, 991, 531))
        self.maingif.setText("")
        self.maingif.setPixmap(QtGui.QPixmap("C:\\Users\\91914\\Project\\GUI files\\Jarvis_Gui (2).gif"))
        self.maingif.setScaledContents(True)
        self.maingif.setObjectName("maingif")
        self.start = QtWidgets.QPushButton(Frame)
        self.start.setGeometry(QtCore.QRect(60, 710, 261, 101))
        self.start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start.setStyleSheet("border-image: url(C:/Users/91914/Project/GUI files/login with border.png);\n"
"background-color: transparent;")
        self.start.setText("")
        self.start.setCheckable(False)
        self.start.setObjectName("start")
        self.exit = QtWidgets.QPushButton(Frame)
        self.exit.setGeometry(QtCore.QRect(660, 710, 261, 101))
        self.exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit.setStyleSheet("background-color: transparent;\n"
"border-image: url(C:/Users/91914/Project/GUI files/exit(with border).png);\n"
"")
        self.exit.setText("")
        self.exit.setObjectName("exit")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
